" break line
set textwidth=72

" Reformat paragraph
nnoremap Q gqap
vnoremap Q gq

" take indent for new line from previous line
set autoindent

" smart autoindenting for C programs
set cindent
set cinoptions=:0,t0,+4,(4

" highlight match while typing search pattern
set incsearch

"ignore case in search patterns
set ignorecase

" no ignore case when pattern has uppercase
set smartcase

" highlight matches with last search pattern
set nohlsearch

" show cursor line and column in the status line
set ruler

" message on status line to show current mode
set showmode

" briefly jump to matching bracket if insert one
set showmatch

" tenths of a second to show matching paren
set matchtime=3

" number of spaces that <Tab> in file uses
set tabstop=8

" number of spaces to use for (auto)indent step
set shiftwidth=8

" use spaces when <Tab> is inserted
" set expandtab

" wrap long lines at a blank
set nolinebreak

" Ignore case in search patterns.
set ignorecase

" allow backspacing over the start of insert
set backspace=2

" the screen contents is NOT restored when exiting Vim
" set t_ti= t_te=
" use .viminfo file upon startup and exiting
set viminfo='50,\"50,n~/.viminfo

" don't give the intro message when starting Vim
set shortmess=I

" recognize function keys in Insert mode
set esckeys

set pastetoggle=<F3>

" syntaxhighlighting
"if has("terminfo")
"  set t_Co=16
"  set t_AB=[%?%p1%{8}%<%t%p1%{40}%+%e%p1%{92}%+%;%dm
"  set t_AF=[%?%p1%{8}%<%t%p1%{30}%+%e%p1%{82}%+%;%dm
"else
"  set t_Co=16
"  set t_Sf=[3%dm
"  set t_Sb=[4%dm
"endif
:syntax on

" Statements bold black
hi Statement cterm=bold ctermfg=Black

set background=dark
colorscheme solarized
