ENV="${HOME}/.kshrc" ; export ENV
[ -r ${HOME}/.xmodmaprc ] && xmodmap ${HOME}/.xmodmaprc
#/home/fab/code/ftray/obj/ftray &
xidle -timeout 500 -program '/usr/local/bin/slock' &
feh --bg-scale ${HOME}/.bg.png &
xcompmgr &
sndiod -v 100 -s default -v 127 -s max
xbacklight -set 15 &
parcellite &
spectrwm
