[ -r ${HOME}/.xmodmaprc ] && xmodmap ${HOME}/.xmodmaprc
redshift-gtk -l 48.77:9.18 -g 0.8 -m randr &
xsetroot -solid AliceBlue
redshift &
pidgin &
parcellite &
/usr/local/libexec/tray-app/battery &
doas /usr/local/libexec/tray-app/eject &
~/bin/fbar &
/home/fab/git/dwm/dwm
# /usr/local/bin/dwm
